export const products = [
  {
    id: 'pastel-cloud-s',
    name: 'Petal Blush',
    category: 'Flowers',
    price: '₦60,000',
    image: '/images/IMG_7229.JPG',
    short: 'A soft pastel bouquet with lilac, white, and pink chrysanthemums.',
    description: 'Mixed bouquet (S) made with different colors of chrysanthemums, lilac, white, pink roses, and gypsos.',
    instagramPost: 'https://www.instagram.com/p/DV-wqrvDVVs/?img_index=1',
  },
  {
    id: 'century-of-roses',
    name: 'Century of Roses',
    category: 'Flowers',
    price: '₦700,000 - ₦800,000',
    image: '/images/optimized/century-of-roses.jpg',
    short: 'A dramatic 100-rose arrangement for grand romantic and luxury gifting moments.',
    description: 'A premium rose statement piece featuring 100 roses in red, pink, white, yellow, or purple.',
    instagramPost: 'https://www.instagram.com/p/DV36cdujSiI/',
  },
  {
    id: 'bff-collection',
    name: 'BFF Collection',
    category: 'Flowers',
    price: '₦390,000',
    image: '/images/optimized/bff-collection.jpg',
    short: 'A signature rose collection styled with gypsos lettering for standout gifting.',
    description: 'A premium collection of 50, 75, or 100 roses styled with custom gypsos letters.',
    instagramPost: 'https://www.instagram.com/p/DVi5Wt0l8my/?img_index=1',
  },
  {
    id: 'the-radiant-garden',
    name: 'The Radiant Garden',
    category: 'Flowers',
    price: '₦150,000 - ₦400,000',
    image: '/images/optimized/radiant-garden.jpg',
    short: 'A full mixed bouquet with layered floral textures and a rich premium feel.',
    description: 'Mixed bouquet (L) made with chrysanthemums, lilies, roses, spray roses, and gypsos.',
    instagramPost: 'https://www.instagram.com/p/DW61kFWDT10/?img_index=1',
  },
  {
    id: 'five-roses-fillers',
    name: '5 Roses with Fillers',
    category: 'Flowers',
    price: '₦45,000',
    image: '/images/5_red_roses.jpg',
    short: 'Five fresh roses with delicate fillers.',
    description: 'Five fresh roses beautifully accented with fillers.',
    instagramPost: 'https://www.instagram.com/p/DXMZzASl1xq/',
  },
  {
    id: 'fifty-red-roses',
    name: '50 Red Roses',
    category: 'Flowers',
    price: '₦350,000 - ₦400,000',
    image: '/images/50_red_roses.jpg',
    short: 'Fifty bold red roses — no fillers, all impact.',
    description: 'A bold arrangement of 50 fresh red roses.',
    instagramPost: 'https://www.instagram.com/p/DYXglXtDa--/',
  },
  {
    id: 'roses-with-fillers',
    name: 'Roses with Fillers',
    category: 'Flowers',
    price: '₦94,000',
    image: '/images/roses_with_fillers.jpg',
    short: 'Fresh roses softened with delicate gypso fillers.',
    description: 'Fresh roses beautifully paired with gypso fillers.',
    instagramPost: 'https://www.instagram.com/p/DXKUOPMjVEz/',
  },
  {
    id: 'the-seraphina',
    name: 'The Seraphina',
    category: 'Flowers',
    price: '₦55,000',
    image: '/images/the_seraphina.jpg',
    short: 'Mixed chrysanthemum and rose bouquet.',
    description: 'A delicate mixed bouquet of chrysanthemums and roses.',
    instagramPost: 'https://www.instagram.com/p/DXrSKmQlwsW/',
  },
  {
    id: 'pastel-cloud-l',
    name: 'Pastel Cloud (L)',
    category: 'Flowers',
    price: '₦160,000',
    image: '/images/pastel_cloud.jpg',
    short: 'A voluminous pastel chrysanthemum arrangement — soft and full.',
    description: 'A large, lush bouquet of mixed chrysanthemums in soft pastel tones.',
    instagramPost: 'https://www.instagram.com/p/DXjUwQhDecs/',
  },
  {
    id: 'mixed-box-bouquet',
    name: 'Mixed Box Bouquet',
    category: 'Flowers',
    price: '₦500,000',
    image: '/images/mixed_box_bouquet.jpg',
    short: 'Mixed blooms presented in a luxury gift box.',
    description: 'A premium mixed flower arrangement presented in a luxury box.',
    instagramPost: 'https://www.instagram.com/p/DU6PP_yDZlD/',
  },
  {
    id: 'bloom-no-1',
    name: 'Bloom No. 1',
    category: 'Flowers',
    price: '₦170,000',
    image: '/images/bloom_no_1.jpg',
    short: 'A lush spray rose bouquet — rich colour, gift-ready.',
    description: 'A medium-sized bouquet of lush spray roses.',
    instagramPost: 'https://www.instagram.com/p/DZCpo4tjcmg/',
  },
  {
    id: 'bloom-no-2',
    name: 'Bloom No. 2',
    category: 'Flowers',
    price: '₦75,000',
    image: '/images/bloom_no_2.jpg',
    short: 'A sweet mix of chrysanthemums and spray roses.',
    description: 'A sweet small bouquet combining chrysanthemums and spray roses.',
    instagramPost: 'https://www.instagram.com/p/DZC0pMPjZXK/',
  },
  {
    id: 'condolence-bouquet',
    name: 'Condolence Bouquet',
    category: 'Flowers',
    price: '₦85,000',
    image: '/images/condolence_flowers.jpg',
    short: 'Serene white chrysanthemums — thoughtful and dignified.',
    description: 'A serene medium-sized white chrysanthemum bouquet for condolences.',
    instagramPost: 'https://www.instagram.com/p/DXCi1cDDUzc/',
  },
  {
    id: 'rose-royale',
    name: 'Rosé Royale',
    category: 'Flowers',
    price: '₦440,000',
    image: '/images/rose_royale.jpg',
    short: 'Grand mixed spray roses in rich, vibrant tones.',
    description: 'A grand large bouquet of mixed spray roses in rich, vibrant tones.',
    instagramPost: 'https://www.instagram.com/p/DYeip2_DbVy/',
  },
  {
    id: 'two-fifty-premium-roses',
    name: '250 Premium Roses',
    category: 'Flowers',
    price: '₦2,000,000',
    image: '/images/250_premium_roses.jpg',
    short: 'The ultimate luxury statement — 250 large premium roses.',
    description: 'The ultimate luxury statement — 250 large, fresh premium roses.',
    instagramPost: 'https://www.instagram.com/p/DYzHKNlDRla/',
  },
  {
    id: 'barbie-deluxe-l',
    name: 'Barbie Deluxe (L)',
    category: 'Flowers',
    price: '₦210,000 - ₦250,000',
    image: '/images/optimized/barbie-deluxe.jpg',
    short: 'Large mixed bouquet with roses, lilies, and gypso fillers.',
    description: 'Mixed bouquet (L) made with 20 roses, 3 spray roses, 6 lilies, and gypso fillers.',
    instagramPost: 'https://www.instagram.com/p/DWuVT6lDu8v/?img_index=1',
  },
  {
    id: 'barbie-deluxe-s',
    name: 'Barbie Deluxe (S)',
    category: 'Flowers',
    price: '₦100,000',
    image: '/images/barbie_deluxe_small.jpeg',
    short: 'The Barbie Deluxe look in a compact, feminine size.',
    description: 'A compact, feminine take on the Barbie Deluxe — same signature look, smaller size.',
  },
  {
    id: 'mixed-sprayroses-l',
    name: 'Mixed Sprayroses (L)',
    category: 'Flowers',
    price: '₦660,000',
    image: '/images/mixed_spray_rose.jpg',
    short: 'A full, generous mix of spray roses and chrysanthemums.',
    description: 'A full, large bouquet of mixed spray roses, chrysanthemums, and complementary blooms.',
  },
  {
    id: 'scarlet-and-snow',
    name: 'Scarlet and Snow',
    category: 'Flowers',
    price: '₦580,000',
    image: '/images/scarlet_and_snow.jpeg',
    short: 'Bold red and white roses, elegantly finished with gypso.',
    description: 'A bold large bouquet of red and white roses elegantly accented with gypso.',
  },
  {
    id: 'test-bouquet',
    name: 'Test Bouquet',
    category: 'Flowers',
    price: '₦500',
    image: '/images/optimized/just-because.jpg',
    short: 'Internal test product.',
    description: 'Internal test product for payment verification.',
    instagramPost: '',
  },
]

export function parsePriceValue(price, city = '') {
  if (typeof price === 'number') return price
  // Remove thousands-separator commas before stripping non-digits, so "390,000" → 390000 not 390
  const cleaned = String(price).replace(/,/g, '').replace(/[^\d]/g, ' ').trim()
  const parts = cleaned.split(/\s+/).map(Number).filter((n) => Number.isFinite(n) && n > 0)
  if (parts.length === 0) return 0
  if (parts.length === 1) return parts[0]
  // Lagos = lower price, Abuja = higher price
  return city === 'Abuja' ? Math.max(...parts) : Math.min(...parts)
}
